### PR TITLE
- Lab Test Attribute of datatype Text gets saved as false if no value is  provided

### PR DESCRIPTION
**Pull request by SHUJAAT-DEV**
provided, this issue is resolved.
- Added Consts (Constants) Class
- Replace the hardcoded string with Constants in all the controller
classes
- ManageLabTestSample Date Formate issues are also resolved with commit
- Privilege issue in addLabTestResult is resolved.

### CODE REVIEW

**Comment by Ruhanga** [comment]
@SHUJAAT-DEV , it is more meaningful to include the ticket ID in the commit message as advised at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@SHUJAAT-DEV are you still working on this?

**Comment by SHUJAAT-DEV** [comment]
@dkayiwa, This PR is not functional. please review this one link: https://github.com/openmrs/openmrs-module-commonlabtest/pull/8

**Comment by SHUJAAT-DEV** [comment]
@Ruhanga, I have created another PR (https://github.com/openmrs/openmrs-module-commonlabtest/pull/8) according to the link: https://wiki.openmrs.org/display/docs/Pull+Request+Tips. This PR is not functional.

**Pull request closed without merging**
