### PR TITLE
CLM-4: REST > GET Custom Representation not returning mentioned fields

### PR DESCRIPTION
**Pull request by tahiraniazi**
- Fixed bug to fetch selected fields in custom representation
- Added unit tests
- Added one missing line in LabTestResultController.java

### CODE REVIEW

**Comment by dkayiwa** [comment]
@tahiraniazi did you see the merge conflicts?

**Comment by seekme94** [comment]
@tahiraniazi please revert and ensure that there are no merge conflicts. You don't require to change the pom files. The version will be updated from master branch when release is prepared.

**Comment by tahiraniazi** [comment]
@dkayiwa, @seekme94 I have now resolved conflicts. Please review!

**Comment by seekme94** [comment]
@tahiraniazi seems okay now. Merged.

**Pull request merged**
